name = "export-manager-erp"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "export-manager-erp"
database_id = "1e69a13a-8722-448d-92d9-55def2014960"
